//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quiz.Web.DAL.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentAdminEmailNotification
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> AssessmentId { get; set; }
        public bool IsAdminEmailCompletionAlertEnabled { get; set; }
        public string EmailId { get; set; }
    
        public virtual AssessmentDetailMaster AssessmentDetailMaster { get; set; }
    }
}
