//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quiz.Web.DAL.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateAssesmentDetailsForm
    {
        public System.Guid id { get; set; }
        public System.Guid FormId { get; set; }
        public string DisplayFieldName { get; set; }
        public string FieldName { get; set; }
        public string FieldType { get; set; }
        public bool IsMandatory { get; set; }
        public string Values { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string Remarks { get; set; }
        public string ModificationHistory { get; set; }
        public bool IsLocked { get; set; }
        public bool IsEnabled { get; set; }
        public System.DateTime Createddate { get; set; }
        public System.Guid AssessmentId { get; set; }
    }
}
