//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quiz.Web.DAL.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistrationFormControl
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> CustomRegisterId { get; set; }
        public Nullable<System.Guid> InputFieldId { get; set; }
        public string DisplayName { get; set; }
        public string InputValues { get; set; }
        public Nullable<bool> IsMandatory { get; set; }
    
        public virtual InputControlMaster InputControlMaster { get; set; }
        public virtual CustomRegistrationForm CustomRegistrationForm { get; set; }
    }
}
