//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quiz.Web.DAL.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TestEngineEntities : DbContext
    {
        public TestEngineEntities()
            : base("name=TestEngineEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminDetail> AdminDetails { get; set; }
        public virtual DbSet<AssessmentDetailMaster> AssessmentDetailMasters { get; set; }
        public virtual DbSet<AssessmentQuestionBankDetail> AssessmentQuestionBankDetails { get; set; }
        public virtual DbSet<DefaultRegistation> DefaultRegistations { get; set; }
        public virtual DbSet<EligibilityCriteriaDetail> EligibilityCriteriaDetails { get; set; }
        public virtual DbSet<ExamFinalReport> ExamFinalReports { get; set; }
        public virtual DbSet<ExaminerAssessmentDetail> ExaminerAssessmentDetails { get; set; }
        public virtual DbSet<ExaminerMaster> ExaminerMasters { get; set; }
        public virtual DbSet<ExaminerMasterDetail> ExaminerMasterDetails { get; set; }
        public virtual DbSet<QuestionBankMaster> QuestionBankMasters { get; set; }
        public virtual DbSet<QuestionsDetail> QuestionsDetails { get; set; }
        public virtual DbSet<InputControlMaster> InputControlMasters { get; set; }
        public virtual DbSet<RegistrationFormControl> RegistrationFormControls { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<CustomRegistrationForm> CustomRegistrationForms { get; set; }
        public virtual DbSet<UserDetailMaster> UserDetailMasters { get; set; }
        public virtual DbSet<AssessmentUserDetail> AssessmentUserDetails { get; set; }
        public virtual DbSet<CandidateAssesmentDetailsForm> CandidateAssesmentDetailsForms { get; set; }
        public virtual DbSet<UserAssessmentAnswerdetail> UserAssessmentAnswerdetails { get; set; }
        public virtual DbSet<AssesmentMasterDetailsForm> AssesmentMasterDetailsForms { get; set; }
        public virtual DbSet<AssessmentStudentNotification> AssessmentStudentNotifications { get; set; }
        public virtual DbSet<AssessmentAdminEmailNotification> AssessmentAdminEmailNotifications { get; set; }
    
        public virtual ObjectResult<GetDashBoardDetails_Result> GetDashBoardDetails(string starDatetime, string endDatetime)
        {
            var starDatetimeParameter = starDatetime != null ?
                new ObjectParameter("StarDatetime", starDatetime) :
                new ObjectParameter("StarDatetime", typeof(string));
    
            var endDatetimeParameter = endDatetime != null ?
                new ObjectParameter("EndDatetime", endDatetime) :
                new ObjectParameter("EndDatetime", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDashBoardDetails_Result>("GetDashBoardDetails", starDatetimeParameter, endDatetimeParameter);
        }
    }
}
